### ISSUE TITLE
can't activate net-scp-1.2.1, already activated net-scp-2.0.0 (Inspec::Plugin::V2::InstallError)

### ISSUE THREAD

**Issue by prabu28** [srobroek/train-vsphere#1]
# inspec plugin install train-vsphere --log-level=debug
[2020-04-17T11:17:21-05:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-iggy': an existing plugin with that name was loaded via user_gem-loading from inspec-iggy
[2020-04-17T11:17:21-05:00] DEBUG: PluginLoader: refusing to re-register plugin 'train-winrm': an existing plugin with that name was loaded via user_gem-loading from train-winrm
[2020-04-17T11:17:21-05:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-supermarket': an existing plugin with that name was loaded via bundle-loading from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.104/lib/bundles/inspec-supermarket.rb
[2020-04-17T11:17:21-05:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-artifact': an existing plugin with that name was loaded via core-loading from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.104/lib/plugins/inspec-artifact/lib/inspec-artifact.rb
[2020-04-17T11:17:21-05:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-compliance': an existing plugin with that name was loaded via core-loading from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.104/lib/plugins/inspec-compliance/lib/inspec-compliance.rb
[2020-04-17T11:17:21-05:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-habitat': an existing plugin with that name was loaded via core-loading from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.104/lib/plugins/inspec-habitat/lib/inspec-habitat.rb
[2020-04-17T11:17:21-05:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-init': an existing plugin with that name was loaded via core-loading from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.104/lib/plugins/inspec-init/lib/inspec-init.rb
[2020-04-17T11:17:21-05:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-plugin-manager-cli': an existing plugin with that name was loaded via core-loading from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.104/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli.rb
[2020-04-17T11:17:21-05:00] DEBUG: PluginLoader: refusing to re-register plugin 'train-habitat': an existing plugin with that name was loaded via system_gem-loading from train-habitat
[2020-04-17T11:17:21-05:00] DEBUG: PluginLoader: refusing to re-register plugin 'train-aws': an existing plugin with that name was loaded via system_gem-loading from train-aws
[2020-04-17T11:17:21-05:00] DEBUG: PluginLoader: refusing to re-register plugin 'train-winrm': an existing plugin with that name was loaded via user_gem-loading from train-winrm
Traceback (most recent call last):
        22: from /usr/bin/inspec:207:in `<main>'
        21: from /usr/bin/inspec:207:in `load'
        20: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.18.104/bin/inspec:11:in `<top (required)>'
        19: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.104/lib/inspec/base_cli.rb:35:in `start'
        18: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        17: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        16: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        15: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        14: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
        13: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
        12: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        11: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        10: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         9: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.104/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:123:in `install'
         8: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.104/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:364:in `install_from_remote_gem'
         7: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.104/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:412:in `install_attempt_install'
         6: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.104/lib/inspec/plugin/v2/installer.rb:72:in `install'
         5: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.104/lib/inspec/plugin/v2/installer.rb:303:in `install_from_remote_gems'
         4: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.104/lib/inspec/plugin/v2/installer.rb:345:in `install_gem_to_plugins_dir'
         3: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.104/lib/inspec/plugin/v2/installer.rb:345:in `each'
         2: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.104/lib/inspec/plugin/v2/installer.rb:347:in `block in install_gem_to_plugins_dir'
         1: from /opt/inspec/embedded/lib/ruby/2.6.0/rubygems/specification.rb:1414:in `activate'
/opt/inspec/embedded/lib/ruby/2.6.0/rubygems/specification.rb:2292:in `check_version_conflict': can't activate net-scp-1.2.1, already activated net-scp-2.0.0 (Gem::LoadError)
        19: from /usr/bin/inspec:207:in `<main>'
        18: from /usr/bin/inspec:207:in `load'
        17: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.18.104/bin/inspec:11:in `<top (required)>'
        16: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.104/lib/inspec/base_cli.rb:35:in `start'
        15: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        14: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        13: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        12: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        11: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
        10: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
         9: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
         8: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
         7: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         6: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.104/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:123:in `install'
         5: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.104/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:364:in `install_from_remote_gem'
         4: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.104/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:412:in `install_attempt_install'
         3: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.104/lib/inspec/plugin/v2/installer.rb:72:in `install'
         2: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.104/lib/inspec/plugin/v2/installer.rb:303:in `install_from_remote_gems'
         1: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.104/lib/inspec/plugin/v2/installer.rb:344:in `install_gem_to_plugins_dir'
/opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.104/lib/inspec/plugin/v2/installer.rb:353:in `rescue in install_gem_to_plugins_dir': can't activate net-scp-1.2.1, already activated net-scp-2.0.0 (Inspec::Plugin::V2::InstallError)

**Comment by prabu28** [comment]
i have tried all the version on https://rubygems.org/gems/train-vsphere
 none of the plugins seems to be working .

My inspec below .

# inspec version  (core)
4.18.104


if the plugin is not ready for the latest version please let me a working inspec version 

thanks in advance

**Comment by srobroek** [comment]
Odd. I haven’t looked at this in a while so I didn’t check if it’s working with more recent versions of inspec. Will take a look when I’ve got the time.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by prabu28** [comment]
Sure that will be helpfull . mean while i'm using this method 
https://github.com/chef-boneyard/inspec-vmware

**Comment by srobroek** [comment]
Hi, it seems to install fine from my side with the latest version of inspec. 

Looking at your error log it seems that this is the issue:

/opt/inspec/embedded/lib/ruby/2.6.0/rubygems/specification.rb:2292:in check_version_conflict': can't activate net-scp-1.2.1, already activated net-scp-2.0.0 (Gem::LoadError) 19: from /usr/bin/inspec:207:in

Which seems to be related to train (https://rubygems.org/gems/train/versions/0.13.0) which has an explicit dependency on ~> net-scp 1.2.1. 

I remember running into this in the past, what I would recommend trying is to run in a virtualenv with net-scp 1.2.1 installed over net-scp 2.0.0 as this seems to be causing the conflict. Alternatively you could uninstall net-scp 2.0.0 if this is not used anywhere else. 

Let me know how it goes and if I need to help out with anything else!
